package com.gojek.conwaygameoflife;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.SQLOutput;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class ConwayGameOfLife {
    public static void main(String[] args) {
        Universe universe = new Universe(10, 10);
        initializeOscillator(universe);

        Scanner sc = null;

        try {
            sc = new Scanner(new FileInputStream("./input.txt"));
        } catch (FileNotFoundException e){
            System.out.println("File is not found. Please check your input file.");
        }

        while (sc.hasNextLine())
            System.out.println(sc.nextLine());

        for (int i = 0; i < 10; i++) {
            universe.printUniverse();
            universe.updateUniverse();
        }
    }

    public static void initializeOscillator(Universe universe) {
        universe.getGrid()[4][1] = 1;
        universe.getGrid()[4][2] = 1;
        universe.getGrid()[4][3] = 1;
    }

}
