package java;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ConwayGameOfLifeTest {
    /*@Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

   /* @Test public void testInitialize() {
        int[][] arr
        assertEquals();

        arr[4][1] = 1;
        arr[4][2] = 1;
        arr[4][3] = 1;
    }*/
}
