package java;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import com.gojek.conwaygameoflife.ConwayGameOfLife;
import org.junit.Test;
import static org.junit.Assert.*;

public class ConwayGameOfLifeTest {
    /*@Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }*/

    /*@Test public void testInitialize() {
        ConwayGameOfLife classUnderTest = new ConwayGameOfLife();

        int[][] arr = new int[10][10];
        for (int i = 0; i < 10; i++)
            for (int j = 0; j < 10; j++)
                arr[i][j] = 0;

        assertEquals(arr[4][1], 0);
        assertEquals(arr[4][2], 0);
        assertEquals(arr[4][3], 0);

        classUnderTest.initialize(arr);

        assertEquals(arr[4][1], 1);
        assertEquals(arr[4][2], 1);
        assertEquals(arr[4][3], 1);
    }*/
}
